# Generated by Django 4.1.1 on 2022-09-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GoogleSheetModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(verbose_name="Номер заказа")),
                (
                    "price_usd",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="Стоимость,$"
                    ),
                ),
                (
                    "price_rub",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="Стоимость в руб."
                    ),
                ),
                ("delivery_date", models.DateField(verbose_name="Срок поставки")),
            ],
            options={
                "verbose_name": "База заказов",
                "verbose_name_plural": "База заказов",
                "ordering": ["-order"],
            },
        ),
    ]
